### ISSUE TITLE
Navigation Bug With OnAppear

### ISSUE THREAD

**Issue by alicankurtFinago** [Whiffer/SwiftUI-PopToRootExample#3]
I want to start contentView but when on Appear Contentview should go secondView after some Api calls. Like this,

```swift
struct ContentView: View {    
    @State private var isActive = false    
    var body: some View {
        NavigationView{
            VStack{
                Text("ROOT")
                NavigationLink(destination: SecondView(), isActive: $isActive){}
                    .isDetailLink(false)
            }
            .navigationTitle("ROOT")
            .onAppear{
                isActive = true
            }
        }     
        .navigationViewStyle(.stack)
        .environment(\.rootPresentationMode, self.$isActive)        
    }
}
```

But when clicked PopToRoot Button, this bug happens on the GIF;

![Bug Gif](https://user-images.githubusercontent.com/99237756/177271928-5df10515-5fc1-4841-92c3-c605e0b0f518.gif)

**Comment by Whiffer** [comment]
I don't know for sure, but it looks like it might be working as expected.  When your Root view appears, you automatically activate the SECOND VIEW. After manually pushing the THIRD VIEW, you manually pop to Root, which if onAppear fires again, will send it to SECOND VIEW again, and due to the environment, will pop it back to Root.  I have not had good luck with trying to change view state like that in onAppear.  It might be better for you to ask your question on StackOverflow. Be sure to include your complete example code. Otherwise, you might want to check out "The SwiftUI cookbook for navigation" from WWDC22.
